import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { approvalsService } from '../services/approvalsService';

/**
 * The four Approvals queues.
 *
 * `enabled` is the open tab: only the visible list is fetched, so switching tabs
 * costs one request rather than four on mount.
 */
export function usePendingTransfers(enabled) {
  return useQuery({
    queryKey: ['transfers', 'pending'],
    queryFn: approvalsService.pendingTransfers,
    enabled,
  });
}

export function useTransferHistory(enabled) {
  return useQuery({
    queryKey: ['transfers', 'history'],
    queryFn: approvalsService.transferHistory,
    enabled,
  });
}

export function useMyTransferRequests(enabled) {
  return useQuery({
    queryKey: ['transfers', 'mine'],
    queryFn: approvalsService.myTransferRequests,
    enabled,
  });
}

export function useInfoRequests(enabled, params) {
  return useQuery({
    queryKey: ['info-requests', params ?? null],
    queryFn: () => approvalsService.infoRequests(params),
    enabled,
  });
}

/**
 * Every write on this screen.
 *
 * All of them invalidate ALL four queues, not just the one acted on: accepting a
 * pending transfer moves it into history, cancelling one of my requests changes
 * both "mine" and any queue it was pending in. Refreshing only the visible list
 * would leave the other tabs showing a decision that has already been taken.
 *
 * Members and hierarchy caches go too — an accepted transfer moves someone
 * between Sabhas, and an approved info change rewrites their record.
 */
export function useApprovalActions() {
  const qc = useQueryClient();

  const invalidate = () => {
    qc.invalidateQueries({ queryKey: ['transfers'] });
    qc.invalidateQueries({ queryKey: ['info-requests'] });
    qc.invalidateQueries({ queryKey: ['members'] });
    qc.invalidateQueries({ queryKey: ['user'] });
  };

  // Written out rather than generated by a helper: a `make()` that calls
  // useMutation would be a hook call inside a function, which only works by
  // accident of call order and breaks the moment one becomes conditional.
  const acceptTransfer = useMutation({
    mutationFn: ({ id, sabhaId, followupId }) =>
      approvalsService.acceptTransfer(id, { sabhaId, followupId }),
    onSuccess: invalidate,
  });
  const rejectTransfer = useMutation({
    mutationFn: ({ id, reason }) => approvalsService.rejectTransfer(id, reason),
    onSuccess: invalidate,
  });
  const cancelTransfer = useMutation({
    mutationFn: ({ id, reason }) => approvalsService.cancelTransfer(id, reason),
    onSuccess: invalidate,
  });
  const approveInfo = useMutation({
    mutationFn: ({ id, overrides, remarks }) =>
      approvalsService.approveInfoRequest(id, { overrides, remarks }),
    onSuccess: invalidate,
  });
  const rejectInfo = useMutation({
    mutationFn: ({ id, remarks }) => approvalsService.rejectInfoRequest(id, remarks),
    onSuccess: invalidate,
  });
  const cancelInfo = useMutation({
    mutationFn: ({ id, remarks }) => approvalsService.cancelInfoRequest(id, remarks),
    onSuccess: invalidate,
  });

  return {
    acceptTransfer, rejectTransfer, cancelTransfer,
    approveInfo, rejectInfo, cancelInfo,
  };
}
