import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { jobsService } from '../services/jobsService';
import { patchRowInList } from '../services/listCache';
import { useServerPagination } from './usePagination';

/**
 * The Job Portal's reads and writes — job posts AND the applications against
 * them, which are two resources with two independent workflows.
 *
 * `enabled` is the caller's JOB_PORTAL:READ check plus the open tab — a tab that
 * is not on screen is not fetched, so switching costs one request rather than
 * four on mount.
 *
 * TWO CACHE KEYS, kept apart on purpose:
 *
 *   ['job-posts', …]        the board, my posts, one post
 *   ['job-applications', …] applied jobs (own, or everyone's — the server decides)
 *
 * Approving an APPLICATION does not change any job post, so it must not
 * invalidate the board — that would refetch up to 100 rows to redraw nothing.
 * The reverse is also true, with one exception noted on `savePost` below.
 */

/** The board — Active vacancies. There is no status argument: see jobsService.list. */
export function useJobPosts(enabled) {
  return useQuery({
    queryKey: ['job-posts', 'board', 'active'],
    queryFn: () => jobsService.list(),
    enabled,
  });
}

export function useMyJobPosts(enabled) {
  return useQuery({
    queryKey: ['job-posts', 'mine'],
    queryFn: () => jobsService.mine(),
    enabled,
  });
}

/**
 * Applications, server-paged in the project's 100-record blocks: the pager
 * shows 10 (or whatever the reader picks) out of the block already in hand and
 * only asks for the next hundred when the reader walks off the end of this one.
 *
 * One hook for both audiences, because there is one endpoint: the caller's own
 * applications, or every member's if they hold JOB_PORTAL:APPROVE. The server
 * decides — there is no scope to pass, and therefore no scope in the key.
 */
export function useJobApplications({ status, jobId } = {}, enabled) {
  return useServerPagination({
    queryKey: ['job-applications'],
    fetchBlock: (params) => jobsService.applications(params),
    params: {
      status: status || undefined,
      jobId: jobId ?? undefined,
    },
    enabled,
  });
}

/**
 * Every write on the screen.
 *
 * ⚠ `useJobPostMutations`, not `useJobMutations` — that name is already taken by
 * the member form's own job-history writes (`/users/{id}/jobs`), which are a
 * different resource entirely: what a member does for a living, not a vacancy on
 * the board. The two used to collide in the hooks barrel.
 *
 * WHAT REFETCHES AND WHAT DOES NOT. A write that moves a row BETWEEN lists has
 * to invalidate — approving a Pending post takes it out of the review queue and
 * puts it on the Active board, and no local patch can express "this row now
 * belongs to a list you are not looking at". A write that only changes fields
 * of a row already on screen is patched into the cache instead, which is the
 * difference between one request and two.
 */
export function useJobPostMutations() {
  const qc = useQueryClient();
  const invalidatePosts = () => qc.invalidateQueries({ queryKey: ['job-posts'] });
  const invalidateApplications = () => qc.invalidateQueries({ queryKey: ['job-applications'] });

  /** Merge changed fields into every cached copy of one job post row. */
  const patchPost = (jobId, changes) => {
    qc.setQueriesData({ queryKey: ['job-posts'] }, (data) =>
      patchRowInList(data, jobId, changes, { idKey: 'job_id' })
    );
  };

  // Written out rather than generated by a helper: a `make()` calling
  // useMutation would be a hook call inside a function, which only works by
  // accident of call order.
  const savePost = useMutation({
    mutationFn: ({ id, payload }) =>
      id ? jobsService.update(id, payload) : jobsService.create(payload),
    onSuccess: (res, { id }) => {
      // An EDIT returns the whole updated post, so the cached row can be
      // replaced outright. A CREATE is a row that does not exist in any cached
      // list yet — nothing to patch, so the lists are invalidated.
      if (id && res?.data) patchPost(id, res.data);
      else invalidatePosts();
    },
  });

  /**
   * Applying changes the post's `my_application_status` / `can_apply` and
   * nothing else about it, so the board is patched rather than refetched. The
   * APPLICATION lists do gain a row, so those are invalidated.
   */
  const applyToPost = useMutation({
    mutationFn: ({ id, contact }) => jobsService.apply(id, contact),
    onSuccess: (res, { id }) => {
      patchPost(id, {
        my_application_id: res?.data?.application_id ?? null,
        my_application_status: res?.data?.status ?? 'Pending',
        can_apply: false,
      });
      invalidateApplications();
    },
  });

  // Closing moves the post off the Active board and into a different status
  // bucket — a between-lists move, so it invalidates.
  const closePost = useMutation({
    mutationFn: ({ id, remarks }) => jobsService.close(id, remarks),
    onSuccess: invalidatePosts,
  });

  // No post-approval mutation. `PATCH /{id}/approval` exists and jobsService
  // documents it, but no screen changes a post's status — the Review button was
  // removed from the detail dialog. Add one here if that changes; do not reach
  // for the service directly from a component.

  return { savePost, applyToPost, closePost };
}

/**
 * Deciding one application.
 *
 * The row stays in the same list — the management queue shows every status —
 * so the new status is patched into the cached page rather than refetched. It
 * also changes whether the APPLICANT may see the employer's contact details,
 * which lives on the job post's `my_application_status`; that only matters to
 * the applicant's own session, so the board is left alone here.
 */
export function useJobApplicationMutations() {
  const qc = useQueryClient();

  const decide = useMutation({
    mutationFn: ({ id, status }) => jobsService.setApplicationApproval(id, status),
    onSuccess: (res, { id }) => {
      const changes = res?.data;
      if (!changes) {
        qc.invalidateQueries({ queryKey: ['job-applications'] });
        return;
      }
      qc.setQueriesData({ queryKey: ['job-applications'] }, (data) =>
        patchRowInList(data, id, changes, { idKey: 'application_id' })
      );
    },
  });

  return { decide };
}
